### ISSUE TITLE
Hellooo

### ISSUE THREAD

**Issue by johngebbie** [chrisseto/Sux#1]
I was planning to write a terminal *single*-plexer and had the look to see if it had been done before and lo and behold hello! I was even gonna write it in go!

Can I ask what you were up to 7/8 years ago? What was your goal and what state is Sux in?

Thank you. I'm gonna have a look over the source and give it a go.

**Comment by chrisseto** [comment]
Hey @JohnGebbie! Thanks for reaching out.

~7-8 years ago, I was picking up go for the first time and wanted a project to play around with. 
The project I was working on required running a lot of random services. It happened to be written in python, so we couldn't easily fire off goroutines to run everything for us. We had a docker-compose file but given that we all used macbooks, there was a pretty hefty overhead. That lead me to start sux, a simple CLI tool that would run multiple commands and only take up a single terminal window or pane.

I didn't get particularly far with the project. I opted to write everything from scratch and the [parser for escape codes](https://vt100.net/emu/dec_ansi_parser), the `pansi` package, ended up being much more complex than I expected.

I also vaguely recall building a ring buffer to store output ala tmux's scrollback buffers which, in turn, lead me to reading a lot of tmux's source and discovering how much heavy lifting needs to be done.

I _think_ the code will work with very simple programs (`yes`, `cat`) but that's about it.

I wouldn't mind revisiting the project. I still haven't found a good solution for projects that require a lot of services that don't have to be run via docker.

**Comment by johngebbie** [comment]
14 days ago! oh dear oh dear. Thanks for the nice reply @chrisseto, your project is much more ambitious than mine and I thought I'd reply with mine finished days ago but I'm still working on it. Hope to give you a better response soon.

**Comment by johngebbie** [comment]
Hi @chrisseto, sorry so long again.

I develop voice control which I use instead of a keyboard
(https://numenvoice.com) and I was looking for a way to select text on my
terminal (was using urxvt-perls but trying to do better) and found you could
use tmux. I don't really care for the terminal split screen stuff when using
a tiling window manager, so thought I could write a wrapper for your terminal
that just lets you pipe the buffer to an external command, in this case a
keyboard selection program.  So my idea was really just tmux without much
multiplexing and I see now quite different from yours.

I just released the keyboard selection program:
	https://git.sr.ht/~geb/hjkl

And here is my multiplexer experiment:
	https://git.sr.ht/~geb/tsux
but I think there would be a lot more work to get it perfect.

In the end I think I'll maintain a patched version of st like in the hjkl readme,
and it will be part of the desktop environment.

Also, I happened to see this repo that kind of sounds like what you were going for:
	https://github.com/lydell/run-pty
but haven't tried it at all.
